# Defines which nodes are used in the system and how to connect to them.
# All names must be unique.
# No other nodes are known.
# These names will be used for src and dest addresses for the message.Message
# The local node’s name is included in this list
configuration :
  - name : alice
    IP : localhost
    port : 60000 # This is the incoming port on which MP will listen
# May be ephemeral for further communication as usual
  - name : bob
    IP : localhost
    port : 60001
  - name : charlie
    IP : localhost
    port : 60002
  - name : daph
    IP : localhost
    port : 60003
sendRules :
  - action : drop # Ack message number 4 from bob to alice will not be sent
    src : bob
    dest : alice
    kind : Ack
    seqNum : 4
  - action : dropAfter # Daphnie will stop sending Reply messages after seq#6
    kind : Reply
    src : daphnie
    seqNum : 6
  - action: drop
    kind: dr
  - action: duplicate
    kind: du
  - action: dropAfter
    kind: da
    seqNum: 3
  - action: delay
    kind: de
  - action: duplicate
    kind: rdd
receiveRules :
  - action : duplicate # 4th message from Charlie that anyone
    src : charlie # receives will be duplicated
    seqNum : 3
  - action : drop # For the 8th message from Charlie, only the
    src : charlie # original will be received. The duplicate
    seqNum : 7 # will get dropped
    duplicate : True
  - action : delay # Any message from Daphnie will be delivered only
    src : daphnie # after some other message
  - action: drop
    kind: rdr
  - action: duplicate
    kind: rdu
  - action: dropAfter
    kind: rda
    seqNum: 3
  - action: delay
    kind: rde
  - action: duplicate
    kind: rdd
    duplicate: true
  - action: drop
    kind: du